import { getLocale } from "@/lib/locale";
import { getDatasetCount } from "@/lib/db/queries/datasets";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import Link from "next/link";

const DATA_SOURCES = [
  {
    name: "Actes criminels",
    url: "https://donnees.montreal.ca/dataset/actes-criminels",
    desc: "Crime incidents by category, borough, date",
  },
  {
    name: "Info-Travaux",
    url: "https://donnees.montreal.ca/dataset/info-travaux",
    desc: "Active construction sites and road work",
  },
  {
    name: "Requêtes 311",
    url: "https://donnees.montreal.ca/dataset/requete-311",
    desc: "Citizen service requests",
  },
  {
    name: "Permis de construction",
    url: "https://donnees.montreal.ca/dataset/permis-construction",
    desc: "Building permits issued since 1990",
  },
  {
    name: "Entraves à la circulation",
    url: "https://donnees.montreal.ca/dataset/entraves-circulation",
    desc: "Real-time road obstructions",
  },
  {
    name: "Interventions pompiers",
    url: "https://donnees.montreal.ca/dataset/interventions-service-securite-incendie-montreal",
    desc: "Fire department interventions",
  },
  {
    name: "Nids-de-poule",
    url: "https://donnees.montreal.ca/dataset/refection-de-chaussee-par-remplissage-mecanise-de-nid-de-poule",
    desc: "Pothole repairs (SIRR network)",
  },
  {
    name: "Remorquages",
    url: "https://donnees.montreal.ca/dataset/remorquages-de-vehicules-genants",
    desc: "Vehicle towings",
  },
  {
    name: "Punaises de lit",
    url: "https://donnees.montreal.ca/dataset/declarations-exterminations-punaises-de-lit",
    desc: "Bedbug extermination reports",
  },
  {
    name: "Contrats",
    url: "https://ville.montreal.qc.ca/vuesurlescontrats/",
    desc: "Municipal contracts and procurement",
  },
];

export default async function AboutPage() {
  const locale = await getLocale();
  const datasetCount = await getDatasetCount();
  const isFr = locale === "fr";

  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">
          {isFr ? "À propos" : "About"}
        </h1>
        <p className="mt-2 text-muted-foreground">
          {isFr
            ? "MTL Pulse — Le pouls de Montréal en données ouvertes"
            : "MTL Pulse — Montreal's civic pulse in open data"}
        </p>
      </div>

      <Card>
        <CardHeader>
          <h2 className="text-lg font-semibold">
            {isFr ? "Qu'est-ce que MTL Pulse ?" : "What is MTL Pulse?"}
          </h2>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm leading-relaxed">
            {isFr
              ? "MTL Pulse est un tableau de bord civique qui agrège les données ouvertes de la Ville de Montréal. Nous calculons des indicateurs quotidiens (criminalité, travaux, demandes 311, permis, etc.), générons des résumés par intelligence artificielle et présentons les tendances sous forme de graphiques et de cartes."
              : "MTL Pulse is a civic dashboard that aggregates open data from the City of Montreal. We compute daily indicators (crime, construction, 311 requests, permits, etc.), generate AI summaries, and present trends through charts and maps."}
          </p>
          <p className="text-sm leading-relaxed">
            {isFr
              ? "L'objectif : donner aux Montréalais une vue claire et à jour de ce qui se passe dans leur ville et leur arrondissement."
              : "The goal: give Montrealers a clear, up-to-date view of what's happening in their city and borough."}
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <h2 className="text-lg font-semibold">
            {isFr ? "Méthodologie" : "Methodology"}
          </h2>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm leading-relaxed">
            {isFr
              ? "Les données sont ingérées quotidiennement depuis le portail Données Montréal (CKAN) et d'autres APIs. Chaque source suit un pipeline : récupération → normalisation → déduplication → stockage. Les métriques sont calculées à partir des tables brutes et stockées dans une table agrégée pour des requêtes rapides."
              : "Data is ingested daily from the Montreal Open Data portal (CKAN) and other APIs. Each source follows a pipeline: fetch → normalize → deduplicate → store. Metrics are computed from raw tables and stored in an aggregated table for fast queries."}
          </p>
          <p className="text-sm leading-relaxed">
            {isFr
              ? "Les résumés quotidiens et hebdomadaires sont générés par Claude (Anthropic) à partir des métriques calculées. Ils sont produits en français et en anglais."
              : "Daily and weekly digests are generated by Claude (Anthropic) from computed metrics. They are produced in French and English."}
          </p>
          <p className="text-sm text-amber-600 dark:text-amber-500">
            {isFr
              ? "Les résumés IA sont informatifs mais peuvent contenir des imprécisions. Utilisez-les comme point de départ, pas comme source unique."
              : "AI summaries are informative but may contain inaccuracies. Use them as a starting point, not as a sole source."}
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <h2 className="text-lg font-semibold">
            {isFr ? "Sources de données" : "Data sources"}
          </h2>
          <p className="text-sm text-muted-foreground">
            {isFr
              ? `Actuellement ${datasetCount > 0 ? datasetCount : "16+"} jeux de données suivis.`
              : `Currently tracking ${datasetCount > 0 ? datasetCount : "16+"} datasets.`}
          </p>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {DATA_SOURCES.map((ds) => (
              <li key={ds.url}>
                <a
                  href={ds.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm font-medium text-orange hover:underline"
                >
                  {ds.name}
                </a>
                <p className="text-xs text-muted-foreground">{ds.desc}</p>
              </li>
            ))}
          </ul>
          <p className="mt-4 text-sm text-muted-foreground">
            {isFr ? (
              <>
                Portail principal :{" "}
                <a
                  href="https://donnees.montreal.ca"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-orange hover:underline"
                >
                  donnees.montreal.ca
                </a>
              </>
            ) : (
              <>
                Main portal:{" "}
                <a
                  href="https://donnees.montreal.ca"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-orange hover:underline"
                >
                  donnees.montreal.ca
                </a>
              </>
            )}
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <h2 className="text-lg font-semibold">
            {isFr ? "Attribution" : "Attribution"}
          </h2>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">
            {isFr
              ? "Données sous licence CC BY 4.0 — Ville de Montréal. Vous pouvez réutiliser, modifier et diffuser ces données en citant la source."
              : "Data under CC BY 4.0 license — City of Montreal. You may reuse, modify and distribute these data with attribution."}
          </p>
        </CardContent>
      </Card>

      <div className="pt-4">
        <Link
          href="/"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← {isFr ? "Accueil" : "Home"}
        </Link>
      </div>
    </div>
  );
}
